use bugbee_core::{Finding, Location, PocClass, ProofOfConcept, Severity, SourceKind};
#[allow(unused_imports)]
use bugbee_llm::{ChatMessage, ChatRequest, LlmClient};
use serde::Deserialize;
use tracing::{debug, warn};

/// A hypothesis generated by the LLM about a potential vulnerability.
#[derive(Debug, Clone, Deserialize)]
pub struct Hypothesis {
    #[serde(default)]
    pub cwe_id: String,
    #[serde(default)]
    pub title: String,
    #[serde(default)]
    pub description: String,
    /// The injection point (parameter, header, body field, path)
    #[serde(default)]
    pub injection_point: String,
    /// Why it's vulnerable
    #[serde(default)]
    pub reasoning: String,
    /// A test payload to verify
    #[serde(default)]
    pub payload: String,
    /// Expected behavior if vulnerable
    #[serde(default)]
    pub expected_behavior: String,
    #[serde(default)]
    pub severity: String,
    #[serde(default)]
    pub endpoint: String,
}

/// Parse LLM JSON response into a list of hypotheses.
/// Returns graceful fallback (empty vec) on malformed input — never panics.
pub fn parse_hypotheses(input: &str) -> Vec<Hypothesis> {
    if input.trim().is_empty() {
        return Vec::new();
    }

    // Try direct array parse
    if let Ok(arr) = serde_json::from_str::<Vec<Hypothesis>>(input) {
        if !arr.is_empty() {
            return arr;
        }
    }

    // Try extracting JSON array from surrounding text
    if let Some(start) = input.find('[') {
        if let Some(end) = input.rfind(']') {
            let slice = &input[start..=end];
            if let Ok(arr) = serde_json::from_str::<Vec<Hypothesis>>(slice) {
                if !arr.is_empty() {
                    return arr;
                }
            }
        }
    }

    // Try single object
    if input.trim().starts_with('{') {
        if let Ok(single) = serde_json::from_str::<Hypothesis>(input.trim()) {
            return vec![single];
        }
    }

    // Try extracting from ```json ... ``` blocks
    for block in input.split("```") {
        let block = block.trim();
        if let Some(json) = block.strip_prefix("json\n").or_else(|| block.strip_prefix("json\r\n")) {
            if let Ok(arr) = serde_json::from_str::<Vec<Hypothesis>>(json) {
                return arr;
            }
            if let Ok(single) = serde_json::from_str::<Hypothesis>(json) {
                return vec![single];
            }
        }
    }

    warn!("parse_hypotheses: failed to parse LLM output, returning empty");
    debug!("parse_hypotheses raw input: {}", &input[..input.len().min(500)]);
    Vec::new()
}

/// Convert hypotheses into Finding objects.
pub fn hypotheses_to_findings(hypotheses: &[Hypothesis], default_endpoint: &str) -> Vec<Finding> {
    hypotheses
        .iter()
        .enumerate()
        .map(|(i, h)| {
            let severity = parse_severity(&h.severity);
            let loc = Location::line(
                if h.endpoint.is_empty() {
                    default_endpoint
                } else {
                    &h.endpoint
                },
                1,
            );
            let mut finding = Finding::new(
                format!("llm-hypothesis-{}", h.cwe_id),
                if h.title.is_empty() {
                    format!("Potential vulnerability #{}", i + 1)
                } else {
                    h.title.clone()
                },
                if h.description.is_empty() {
                    h.reasoning.clone()
                } else {
                    h.description.clone()
                },
                severity,
                SourceKind::Agent,
                loc,
            );
            finding.cwe = Some(h.cwe_id.clone());
            finding.poc = Some(ProofOfConcept::new(
                PocClass::Other,
                vec![
                    format!("Reasoning: {}", h.reasoning),
                    format!("Injection point: {}", h.injection_point),
                    format!("Payload: {}", h.payload),
                    format!("Expected: {}", h.expected_behavior),
                ],
                None,
            ));
            finding
        })
        .collect()
}

fn parse_severity(s: &str) -> Severity {
    match s.to_ascii_lowercase().trim() {
        "critical" | "crit" => Severity::Critical,
        "high" => Severity::High,
        "medium" | "med" => Severity::Medium,
        "low" => Severity::Low,
        _ => Severity::Info,
    }
}

/// Build a prompt that asks the LLM to analyze an endpoint for vulnerabilities.
pub fn build_hunt_prompt(endpoint: &str, method: &str, params: &[String]) -> String {
    format!(
        r#"You are a security researcher analyzing this endpoint:

Method: {method}
Endpoint: {endpoint}
Parameters: {params}

Identify potential vulnerabilities. For each:
1. CWE ID (e.g., CWE-89, CWE-79, CWE-78)
2. Title
3. Description
4. Injection point (parameter, header, body field)
5. Reasoning — why it's vulnerable
6. A test payload
7. Expected behavior if vulnerable
8. Severity (Critical/High/Medium/Low/Info)

Output as a JSON array. Example:
[
  {{
    "cwe_id": "CWE-89",
    "title": "SQL Injection in username parameter",
    "description": "The username parameter is directly interpolated into a SQL query",
    "injection_point": "username",
    "reasoning": "No input sanitization visible, parameter reflected in error messages",
    "payload": "' OR 1=1 --",
    "expected_behavior": "Authentication bypass or database error disclosure",
    "severity": "Critical",
    "endpoint": "{method} {endpoint}"
  }}
]"#,
        method = method,
        endpoint = endpoint,
        params = params.join(", "),
    )
}

/// Mock LLM provider for testing — returns pre-configured responses.
pub struct MockLlmClient {
    pub responses: std::sync::Mutex<Vec<String>>,
    pub requests: std::sync::Mutex<Vec<ChatRequest>>,
}

impl MockLlmClient {
    pub fn new(responses: Vec<String>) -> Self {
        Self {
            responses: std::sync::Mutex::new(responses),
            requests: std::sync::Mutex::new(Vec::new()),
        }
    }
}

#[async_trait::async_trait]
impl LlmClient for MockLlmClient {
    fn name(&self) -> &str {
        "mock"
    }

    fn model(&self) -> &str {
        "mock-v1"
    }

    async fn chat(&self, request: ChatRequest) -> bugbee_core::Result<bugbee_llm::ChatResponse> {
        self.requests.lock().unwrap().push(request);
        let response = self
            .responses
            .lock()
            .unwrap()
            .pop()
            .unwrap_or_else(|| "[]".to_string());
        Ok(bugbee_llm::ChatResponse {
            content: response,
            model: "mock-v1".into(),
            tool_calls: vec![],
            finish_reason: Some("stop".into()),
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // ── parseHypotheses: known-good JSON ──────────────────────────

    #[test]
    fn test_parse_valid_array() {
        let json = r#"[
            {"cwe_id": "CWE-89", "title": "SQLi", "injection_point": "id", "reasoning": "no filter", "payload": "' OR 1=1", "expected_behavior": "bypass", "severity": "Critical", "endpoint": "GET /api"}
        ]"#;
        let hypotheses = parse_hypotheses(json);
        assert_eq!(hypotheses.len(), 1);
        assert_eq!(hypotheses[0].cwe_id, "CWE-89");
        assert_eq!(hypotheses[0].severity, "Critical");
    }

    #[test]
    fn test_parse_multiple_findings() {
        let json = r#"[
            {"cwe_id": "CWE-89", "title": "SQLi", "injection_point": "id", "reasoning": "test", "payload": "'", "expected_behavior": "error", "severity": "High", "endpoint": "/api"},
            {"cwe_id": "CWE-79", "title": "XSS", "injection_point": "name", "reasoning": "test", "payload": "<script>", "expected_behavior": "exec", "severity": "Medium", "endpoint": "/api"}
        ]"#;
        let hypotheses = parse_hypotheses(json);
        assert_eq!(hypotheses.len(), 2);
        assert_eq!(hypotheses[1].cwe_id, "CWE-79");
    }

    // ── parseHypotheses: deliberately malformed JSON ──────────────

    #[test]
    fn test_parse_empty_string() {
        let hypotheses = parse_hypotheses("");
        assert_eq!(hypotheses.len(), 0);
    }

    #[test]
    fn test_parse_garbage() {
        let hypotheses = parse_hypotheses("this is not json at all !@#$%");
        assert_eq!(hypotheses.len(), 0);
    }

    #[test]
    fn test_parse_partial_json() {
        let hypotheses = parse_hypotheses("{broken json");
        assert_eq!(hypotheses.len(), 0);
    }

    #[test]
    fn test_parse_empty_array() {
        let hypotheses = parse_hypotheses("[]");
        assert_eq!(hypotheses.len(), 0);
    }

    #[test]
    fn test_parse_non_array_object() {
        let json = r#"{"cwe_id": "CWE-89", "title": "SQLi", "injection_point": "id", "reasoning": "test", "payload": "'", "expected_behavior": "bypass", "severity": "Critical"}"#;
        let hypotheses = parse_hypotheses(json);
        assert_eq!(hypotheses.len(), 1);
    }

    #[test]
    fn test_parse_missing_fields() {
        // Missing optional fields should still produce a valid Hypothesis
        let json = r#"[
            {"cwe_id": "CWE-89"}
        ]"#;
        let hypotheses = parse_hypotheses(json);
        assert_eq!(hypotheses.len(), 1);
        assert_eq!(hypotheses[0].cwe_id, "CWE-89");
        assert!(hypotheses[0].title.is_empty());
    }

    #[test]
    fn test_parse_markdown_code_block() {
        let md = r#"Here are the findings:

```json
[
    {"cwe_id": "CWE-89", "title": "SQLi", "injection_point": "id", "reasoning": "no filter", "payload": "' OR 1=1", "expected_behavior": "bypass", "severity": "Critical", "endpoint": "GET /api"}
]
```"#;
        let hypotheses = parse_hypotheses(md);
        assert_eq!(hypotheses.len(), 1);
        assert_eq!(hypotheses[0].cwe_id, "CWE-89");
    }

    #[test]
    fn test_parse_json_with_extra_text() {
        let text = r#"Some text before...
[
    {"cwe_id": "CWE-78", "title": "CMDi", "injection_point": "host", "reasoning": "shell metacharacters allowed", "payload": "; id", "expected_behavior": "command output", "severity": "Critical", "endpoint": "POST /ping"}
]
...and some text after"#;
        let hypotheses = parse_hypotheses(text);
        assert_eq!(hypotheses.len(), 1);
    }

    // ── hypotheses_to_findings ────────────────────────────────────

    #[test]
    fn test_hypotheses_to_findings_conversion() {
        let hypotheses = vec![
            Hypothesis {
                cwe_id: "CWE-89".into(),
                title: "SQL Injection".into(),
                description: "Test desc".into(),
                injection_point: "id".into(),
                reasoning: "no sanitization".into(),
                payload: "' OR 1=1".into(),
                expected_behavior: "bypass".into(),
                severity: "Critical".into(),
                endpoint: "GET /api/users".into(),
            },
        ];
        let findings = hypotheses_to_findings(&hypotheses, "http://localhost:8080");
        assert_eq!(findings.len(), 1);
        assert_eq!(findings[0].severity, Severity::Critical);
        assert_eq!(findings[0].cwe.as_deref(), Some("CWE-89"));
        assert!(findings[0].poc.is_some());
    }

    #[test]
    fn test_hypotheses_to_findings_empty() {
        let findings = hypotheses_to_findings(&[], "http://localhost:8080");
        assert_eq!(findings.len(), 0);
    }

    #[test]
    fn test_hypotheses_to_findings_default_endpoint() {
        let hypotheses = vec![Hypothesis {
            cwe_id: "CWE-79".into(),
            title: "XSS".into(),
            description: String::new(),
            injection_point: String::new(),
            reasoning: "reflected input".into(),
            payload: "<script>".into(),
            expected_behavior: "exec".into(),
            severity: "High".into(),
            endpoint: String::new(), // empty — should use default
        }];
        let findings = hypotheses_to_findings(&hypotheses, "http://localhost:8080/search");
        assert_eq!(findings.len(), 1);
        assert_eq!(findings[0].location.path, "http://localhost:8080/search");
    }

    // ── build_hunt_prompt ─────────────────────────────────────────

    #[test]
    fn test_build_hunt_prompt() {
        let prompt = build_hunt_prompt("http://localhost:8080/login", "POST", &["username".into(), "password".into()]);
        assert!(prompt.contains("CWE-89"));
        assert!(prompt.contains("username"));
        assert!(prompt.contains("POST"));
        assert!(prompt.contains("http://localhost:8080/login"));
    }

    // ── Mock LLM integration ──────────────────────────────────────

    #[tokio::test]
    async fn test_mock_llm_returns_expected() {
        let client = MockLlmClient::new(vec![
            r#"[
                {"cwe_id": "CWE-89", "title": "SQLi", "injection_point": "id", "reasoning": "test", "payload": "'", "expected_behavior": "error", "severity": "High", "endpoint": "/api"}
            ]"#.into(),
        ]);
        let req = ChatRequest::new(vec![ChatMessage::user("test")]);
        let resp = client.chat(req).await.unwrap();
        let hypotheses = parse_hypotheses(&resp.content);
        assert_eq!(hypotheses.len(), 1);
        assert_eq!(hypotheses[0].cwe_id, "CWE-89");
    }

    #[tokio::test]
    async fn test_mock_llm_records_request() {
        let client = MockLlmClient::new(vec!["[]".into()]);
        let req = ChatRequest::new(vec![ChatMessage::user("analyze this")]);
        let _ = client.chat(req.clone()).await.unwrap();
        let requests = client.requests.lock().unwrap();
        assert_eq!(requests.len(), 1);
        assert_eq!(requests[0].messages.len(), 1);
    }

    // ── parse_severity ────────────────────────────────────────────

    #[test]
    fn test_parse_severity_values() {
        assert_eq!(parse_severity("Critical"), Severity::Critical);
        assert_eq!(parse_severity("crit"), Severity::Critical);
        assert_eq!(parse_severity("High"), Severity::High);
        assert_eq!(parse_severity("Medium"), Severity::Medium);
        assert_eq!(parse_severity("med"), Severity::Medium);
        assert_eq!(parse_severity("Low"), Severity::Low);
        assert_eq!(parse_severity("Info"), Severity::Info);
        assert_eq!(parse_severity("unknown"), Severity::Info);
        assert_eq!(parse_severity(""), Severity::Info);
    }
}
